version: '3.3'

services: 
  app:
    build: ./app
    restart: always
    links:
      - "mongo"
    working_dir: "/src"
    tty: true
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: hoge
      MONGO_INITDB_ROOT_PASSWORD: hoge
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    